version: '3.9'
services:
    nginx-todolist:
        image: nginx:stable-alpine
        container_name: nginx-container-todolist
        ports:
            -  "8000:80"
        volumes:
            -   ./app:/var/www/project
            -   ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php8-todolist
            -   mysql-todolist
        networks:
            dev:

    php8-todolist:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php8-container-todolist
        depends_on:
            -   mysql-todolist
        ports:
            -   "9000:9000"
        volumes:
            -   ./app:/var/www/project
            -   ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            dev:

    mysql-todolist:
        platform: linux/x86_64
        image: mysql:latest
        container_name: mysql-container-todolist
        restart: always
        ports:
        -   "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            dev:
        volumes:
            -   ./mysql:/var/lib/mysql

    blackfire:
        image: blackfire/blackfire:2
        ports: ["8307"]
        restart: always
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: "$S_ID"
            BLACKFIRE_SERVER_TOKEN: "$S_TOKEN"
            BLACKFIRE_CLIENT_ID: "$C_ID"
            BLACKFIRE_CLIENT_TOKEN: "$C_TOKEN"
        networks:
            dev:

networks:
    dev:

volumes:
    db-data: